name: CD staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency: staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2	
        with:
          version: 8
          run_install: false

      - name: Get the pnpm store directory
        shell: bash
        run: |
            echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup the pnpm cache
        uses: actions/cache@v3
        with:
            path: ${{ env.STORE_PATH }}
            key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/OcodaWebsiteDeployer
          aws-region: us-east-1

      - name: Deploy stacks
        run: |
          pnpm run deploy

